import { join } from "path";
process.env.NODE_CONFIG_DIR = join(__dirname, "..", "config");

import { readFileSync, writeFileSync } from "fs";
import { pjr } from "../commands";

/**
 * Update the README.md doc
 */
function updateReadme() {
  const pageToc = pjr.toTableOfContents("./docs/commands.md");
  const readmePath = join(__dirname, "..", "..", "README.md");

  const readmeContent = readFileSync(readmePath).toString();
  const updatedReadme = readmeContent.replace(
    /<!-- COMMAND-TOC-START -->.*<!-- COMMAND-TOC-END -->/gs,
    `<!-- COMMAND-TOC-START -->\n${pageToc}\n<!-- COMMAND-TOC-END -->`,
  );
  writeFileSync(readmePath, updatedReadme);
}

/**
 * Write commands markdown document
 */
function writeCommandsPage() {
  const md = pjr.toMarkdownDoc();
  const pageToc = pjr.toTableOfContents();
  const docPath = join(__dirname, "..", "..", "docs", "commands.md");
  const autoGeneratedComment = "<!-- THIS DOCUMENT IS AUTO-GENERATED -->";
  const doc = `${autoGeneratedComment}\n\n# Commands\n\n${pageToc}\n\n${md}`;

  writeFileSync(docPath, doc);
}

writeCommandsPage();
updateReadme();
