import { join } from "path";
process.env.NODE_CONFIG_DIR = join(__dirname, "..", "config");

import { writeFileSync } from "fs";
import { pjr } from "../commands";

const md = pjr.toMarkdownDoc();
const toc = pjr.toTableOfContents();

const docPath = join(__dirname, "..", "..", "docs", "commands.md");
const autoGeneratedComment = "<!-- THIS DOCUMENT IS AUTO-GENERATED -->";
const doc = `${autoGeneratedComment}\n\n# Commands\n\n${toc}\n\n${md}`;

writeFileSync(docPath, doc);
